### ISSUE TITLE
draw_variants

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/genophenocorr#103]
@ielis @lnrekerle 
where do we get the  TranscriptCoordinates object from in code such as the following (see last line)?

```
import genophenocorr
local_path = "/Users/robinp/data/hpo/hp.json"
hpo = hpotk.load_minimal_ontology(local_path)

from genophenocorr.data import get_toy_cohort

cohort = get_toy_cohort()

# Analyze genotype-phenotype associations
from genophenocorr.analysis import configure_cohort_analysis
from genophenocorr.analysis.predicate import BooleanPredicate
from genophenocorr.model import VariantEffect

cohort_analysis = configure_cohort_analysis(cohort, hpo)
frameshift = cohort_analysis.compare_by_variant_effect(VariantEffect.FRAMESHIFT_VARIANT, tx_id='NM_1234.5')

#frameshift.summarize(hpo, phenotype_category=BooleanPredicate.YES)
artist = VariantTranscriptProteinArtist(width=500)

artist.draw_variants(cohort.all_variants, cohort.???)
```

**Comment by ielis** [comment]
That's not yet implemented (Stub is [here](https://github.com/monarch-initiative/genophenocorr/blob/a2e52f271f26b7133850a50ced78c24d9eca30b8/src/genophenocorr/preprocessing/_variant.py#L105)). I thought you'd be all set to develop in the context of the unit test I was showing you the other day. There, you have mock data including `TranscriptCoordinates`.

However, to run the tests within a notebook with real data, you need to get yourself a real `TranscriptCoordinateService` implementation. It's not a :rocket: science: 1) query VEP, and ETL the JSON response into `TranscriptCoordinates`. However, we don't have that yet (#63 ).

**Comment by pnrobinson** [comment]
@ielis 
Maybe it is best to use the UniProt API
We can get exon coordinates
https://www.ebi.ac.uk/proteins/api/doc/#/coordinates
and then say that users need to provide a UniProt accession to use the tool?

**Comment by ielis** [comment]
Either that or Variant Validator, as mentioned in #63
