### ISSUE TITLE
replace phenopackets with phenopackets of phenopacket-store repository

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/genophenocorr#104]
https://github.com/monarch-initiative/phenopacket-store/releases/tag/0.0.1

https://github.com/monarch-initiative/phenopacket-store/blob/main/GetPhenopackets.ipynb

2313 phenopackets!

**Comment by ielis** [comment]
Related to #46

**Comment by ielis** [comment]
Done with #121
