### ISSUE TITLE
genotype_for_sample()

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/genophenocorr#110]
I am not sure why I am seeing this method for Variant, that seems like the wrong place to retrieve the genotype for a sample specified in the argument?

**Comment by ielis** [comment]
It indeed looks a bit weird. The exact details of `Variant` API still need to be worked out.

We need to figure out how to manage 2 states: *individual* variant and *cohort* variant.

The *individual* variant represents data available right after loading phenopacket. We have the `VariantCoordinates` and genotype. The genotype is usually non-homozygous reference.

The *cohort* variant is an aggregation of the data of all cohort members. It includes the `VariantCoordinates`, functional annotation(s), and mapping from `sample_id` -> `genotype`. In contrast with *individual* variant, here the genotype can be `./.` or `0/0`.

I think we can model the `Variant` in a similar fashion to VCF format, where we have 3 levels of information for each variant:
- variant coordinates (CHROM, POS, ID, REF, ALT)
- variant-related data such as functional annotations (INFO)
- genotype-related data - mapping from `sample_id` to `genotype`

All this said, we may need to discuss this further before starting the actual work.

**Comment by pnrobinson** [comment]
@lnrekerle is this still active or can the issue be closed?

**Comment by lnrekerle** [comment]
I think this can be closed since this method no longer exists.
