### ISSUE TITLE
TranscriptAnnotation hgvsc_id

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/genophenocorr#111]
The field hgvsc_id in TranscriptAnnotation seems to have values such as 
```
'NM_001330437.2:c.836A>G'
```

This is not the id it is the actual HGVS cDNA notation. If this is meant to be used as an id, then we should not put the actual mutation into the id, it is confusing. I am assuming that the variable name is wrong and it should be changed to 

hgvs_cdna (also use hgvs_protein)

**Comment by ielis** [comment]
### Requirements

`hgvsc_id` field of the `TranscriptAnnotation` is renamed to `hgvs_cdna`.
