### ISSUE TITLE
Handling phenopackets with legacy CNV

### ISSUE THREAD

**Issue by ielis** [monarch-initiative/genophenocorr#119]
Not all phenopackets include variants with exact CNV coordinates and sometimes all we have is a gene and a Sequence Ontology term (e.g. )

For instance [PMID_36446582_Novara2017_P2](https://github.com/monarch-initiative/phenopacket-store/blob/1e7d0845ebcbba87a78a584a39e0e4d55327bf6f/notebooks/ANKRD11/phenopackets/PMID_36446582_Novara2017_P2.json#L63) includes the following genomic interpretation:

```
"genomicInterpretations": [
          {
            "subjectOrBiosampleId": "Novara, 2017_P2",
            "interpretationStatus": "CAUSATIVE",
            "variantInterpretation": {
              "variationDescriptor": {
                "id": "var_WqTwGolKqoDWrueIvbQUFXsZr",
                "label": "16q24.2-q24.3 (87340135_89335428)x1 (hg19)",
                "geneContext": {
                  "valueId": "HGNC:21316",
                  "symbol": "ANKRD11"
                },
                "moleculeContext": "genomic",
                "structuralType": {
                  "id": "SO:1000029",
                  "label": "chromosomal_deletion"
                },
                "allelicState": {
                  "id": "GENO:0000135",
                  "label": "heterozygous"
                }
              }
            }
          }
        ]
```

We only know about a *chromosomal_deletion* of *ANKRD11*.

We need to devise a strategy for including such CNVs into the analysis.

**Comment by lnrekerle** [comment]
#156 
@ielis @pnrobinson Is this issue needed when we have another that should cover this? Or is the legacy CNV some how different than other structural variants?

**Comment by ielis** [comment]
No, this is indeed a duplicate of #156. Let's close it and deal with the issue elsewhere.
