### ISSUE TITLE
Handle phenopackets with unparsable data

### ISSUE THREAD

**Issue by ielis** [monarch-initiative/genophenocorr#120]
We need a strategy for handling phenopackets that do not include minimal required data for genotype-phenotype correlation analysis.

For instance, a phenopacket [PMID_36446582_Novara2017_P2](https://github.com/monarch-initiative/phenopacket-store/blob/1e7d0845ebcbba87a78a584a39e0e4d55327bf6f/notebooks/ANKRD11/phenopackets/PMID_36446582_Novara2017_P2.json#L63) does not include CNV coordinates, and ends up having no parsable variant.

Other fallible actions include unknown HPO term as of the used ontology.

## Requirements

- errors are reported with phenopacket ID
- ideally all errors are reported, not just the first one
- phenopacket is not included in the analysis

## Suggestion

- define a new exception, e.g. `GenoPhenoParseException(BaseException)` which can be thrown by `PatientCreator`. This enhances the parsing workflow and informs the user that the process is fallible. The exception has fields for sample ID and a list of specific issues.
- revise `PhenopacketPatientCreator` such that `create_patient` function keeps track of the issues, such as unparsable variant, invalid HPO term, ...
- if we encounter any issues, we pack them into the exception and raise it to indicate a failure

**Comment by lnrekerle** [comment]
This was actually part of my "update notebooks" PR that I just pushed. Forgot to add this task as one that would close with it. This is complete.
