### ISSUE TITLE
By disease/by gene

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/genophenocorr#137]
Add a predicate to search for correlations by disease. For instance, the LMNA cohort has 4 or 5 diseases and some of the mutations are associated with individual diseases.

There are several ways we could do this statistically. In principle we could test whether a variant is significantly different in each pair of diseases (which could be ANOVA followed by post hoc pairwise tests). However, the usual question that gets asked is whether a certain variant is associated with one disease, in which case for each variant we can look as see which disease it is most commonly associated with and then test that disease vs all others. I think the setup might be slightly different than for HPOs...

**Comment by ielis** [comment]
- add an optional sequence of diseases to a patient 
- adjust "phenotype" to include HPO or disease ID
- write a boolean predicate that bins the patient to a phenotype category if the patient includes a disease *X*
- write a poly predicate for binning into *n* predefined disease categories (later)
