### ISSUE TITLE
Beta statistical significance testing

### ISSUE THREAD

**Issue by ielis** [monarch-initiative/genophenocorr#139]
- start at the "terminal" phenotypic features - HPO terms that have no descendants in the total set of phenotypic features targeted to test

- For each node
- check if we have _enough_ counts:
  - we want to have HPO yes >2
  - we want to have variant cats >1
  - we want the total count of patients be above certain threshold
  - @pnrobinson will write a script to precalculate the p values to decide if it makes sense to perform Fisher exact test on the counts.

- if the node has "super significance" it may not be necessary to test ancestors.
  - if we know that there is *k* terms and the significance of this node is *<p/k*, this will survive even Bonferroni, so there is probably no point to test the ancestors of this node. The ancestor should be masked and not tested even for the relatives.

- look at the parents, check if the counts have changed to _some_ extent. However, this applies _only_ to a parent, not to all the ancestors

- marginal sum (total number of items in a row/column)

**Comment by lnrekerle** [comment]
@pnrobinson @ielis Is this also covered in the current Multiple Corrections Heuristic Strategy?

**Comment by ielis** [comment]
Yes, this issue is basically the template/draft for the heuristic MTC strategy, hence a duplicate.

We will follow up on this topic in #126
