### ISSUE TITLE
Do we need observation status on `Disease`?

### ISSUE THREAD

**Issue by ielis** [monarch-initiative/genophenocorr#144]
`genophenocorr.model.Disease` includes `is_present` property to indicate if the patient was diagnosed with the disease or not.

I think we may want to drop the `is_present` property and represent the diagnosis simply by adding the `Disease` to the `Patient`.

In result, the `patient.diseases` will provide a sequence of diseases that the patient has been diagnosed with, and we can imply absence of the diagnosis by checking that the disease is not in `patient.diseases`.

However, phenopacket schema includes the `excluded` attribute in the `Disease` message.

@pnrobinson do you think we should keep the `is_present` property on genophenocorr model? Do you see any use case for `disease.is_present == False`?

**Comment by pnrobinson** [comment]
Itt is often important to say that a specific disease was ruled out. I would say adding bool excluded default False would be useful.

**Comment by ielis** [comment]
OK, thanks!
