### ISSUE TITLE
add key with colors and names of protein ffeatures

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/genophenocorr#171]
For each unique feature name, use the same color. If the name is more than 5 characters, use an abbreviation (e.g., "A", "B", etc...) in the main protein figure. 
Add a legend with one row per feature that shows a color box, the abbreviation if any, and the full name

Do the same for the variant class lollipops

**Comment by pnrobinson** [comment]
Looks great! Wow!
PS -- vielleicht so was Ähnliches für die Lollipops?

**Comment by pnrobinson** [comment]
@frehburg 
Please add adjust the title of the graphic.
Protein name should come from     protein_meta.label (and not be the accession number). Also please remove "Working title"!

**Comment by ielis** [comment]
I fixed the title and added the protein name.

**Comment by pnrobinson** [comment]
redundant with https://github.com/monarch-initiative/genophenocorr/issues/124
closing
