### ISSUE TITLE
Number Protein Regions

### ISSUE THREAD

**Issue by lnrekerle** [monarch-initiative/genophenocorr#176]
Update ProteinMetadata so that each Feature has a unique label. 
i.e. - if there are multiple Features labeled "Disordered", they would become "Disordered_1", "Disordered_2", etc. 

Definition of Done (DoD): A unit test is created that has an example protein with multiple Features of the same name, an analysis passes and gets expected output for just one of the Features and it does not test with all of them. 

EDIT: After discussion, we will not be numbering features and will instead list them in a table for users to select. 

New DoD: A proteins table is printed with viewer that lists all protein features and the location on the amino acid strand.

**Comment by ielis** [comment]
Hi @lnrekerle @pnrobinson 

I am not sure if this is a good idea. I do not think we should edit labels assigned by the Uniprot data submitters. This can lead to perplexing situations where the domain labels in our visualizations will be different from what the user sees at Uniprot.

If we want to support testing of just one feature, then we must choose one of the following:
- assign our own ID to each protein feature such that the ID is unique within the `ProteinMetadata`, and write a predicate that operates on this ID
- help the user to figure out the feature coordinates and use `ProtRegionPredicate`

I strongly advise against modification of the data we receive from Uniprot.

**Comment by pnrobinson** [comment]
@ielis 
Note that uniprot is not consistent
For instance: https://www.uniprot.org/uniprotkb/P35555/entry. (Search for "EGF" -- there are 43 numbered domains)
In other cases, the domains are not numbered. 
For downstream use cases, it would be better to treat all EGF as a group and maybe present a table with the positions of each motif so that the use can also correlate according to positions.
I agree we should definitely not **add** numbering.

**Comment by ielis** [comment]
OK, it is sad if Uniprot is not consistent but we cannot update the labels anyway on our side. Therefore, :+1: for 
> I agree we should definitely not add numbering.

Then, to support the following:
> For downstream use cases, it would be better to treat all EGF as a group and maybe present a table with the positions of each motif so that the use can also correlate according to positions.

we can also write a `VariantPredicate` that takes a regular expression, e.g. `EGF-like.*` or a `re.Pattern` (even better), and tests the variant for overlap with any protein feature that matches the pattern.

**Comment by pnrobinson** [comment]
For the graphic, all the motifs need to have the same color and label!
