### ISSUE TITLE
Heuristic sampler vs. `PhenotypeFilter`

### ISSUE THREAD

**Issue by ielis** [monarch-initiative/genophenocorr#194]
Both `MTC_Strategy.HEURISTIC_SAMPLER` and `genophenocorr.analysis.PhenotypeFilter` use `CohortAnalysisConfiguration.min_perc_patients_w_hpo` property to remove the HPO terms present in fewer patients than the threshold value.

We seem to be doing the same thing twice. 

Let's investigate if these are two separate concerns or if we should remove `PhenotypeFilter`.

**Comment by pnrobinson** [comment]
I think that for simplicity we should just offer the HeuristicFilter, but let's call the Heuristicfilter the PhenotypeMtcFilter, that is a better name. So -- we should
1- Delete the Phenotype filter
2. Rename HEURISTIC_SAMPLE to PHENOTYPE_MTC_FILTER

**Comment by ielis** [comment]
Fixed by #221
