### ISSUE TITLE
Show counts of monoallelic and biallelic variants

### ISSUE THREAD

**Issue by ielis** [monarch-initiative/genophenocorr#43]
For a cohort, show counts of the monoallelic and biallelic variants.

**Comment by pnrobinson** [comment]
@ielis 
It would probably be bettter to have a table with also counts according to mutation category and common variants etc. I will start to work on a viewer.

**Comment by lnrekerle** [comment]
@ielis @pnrobinson Do we still want this? Or are the counts we show in the viewer currently enough?

**Comment by ielis** [comment]
I think we will need to revise the way how we model variants and genotypes, but first we must define the specification/requirements.

Let's keep this alive for the time being.

**Comment by pnrobinson** [comment]
I am not sure I understand the issue.
If we are talking about a recessive disease, we can have a homozygous variant (biallelic) or two heterozygous variants (each monoallelic). Also, some diseases rarely can have both dominant or recessive inheritance.
However, these are rare things and probably we do not want to display counts like this by default.

**Comment by ielis** [comment]
Yeah, It is not entirely clear to me anymore what was the motivation behind this issue. It may have become stale.

Let me close it.
