### ISSUE TITLE
Update the notebooks

### ISSUE THREAD

**Issue by ielis** [monarch-initiative/genophenocorr#46]
Update the notebooks with the most recent code.

**Comment by lnrekerle** [comment]
- [ ] KBG
- [ ] SUOX
- [ ] MAPK8IP3
- [ ] RPGRIP1

**Comment by ielis** [comment]
### TODO

- make a folder with 3 notebooks
- the folder has a subfolder `phenopackets`
  - `KBG`
  - `SUOX`
  - ...

TODO - finish
