### ISSUE TITLE
Implement VariantValidator TranscriptCoordinateService

### ISSUE THREAD

**Issue by ielis** [monarch-initiative/genophenocorr#63]
Implement Ensembl TranscriptCoordinateService  - a way to get transcript and exon coordinates from Ensembl API.

**Comment by ielis** [comment]
We should already have this functionality.

**Comment by pnrobinson** [comment]
but don;t we already have information about the Exons etc somewhere? I thought we wanted to import all of this data when the user is setting up the analysis rather than later on?

**Comment by ielis** [comment]
Yes, we don't have this. We have data with respect to a variant, which includes tx id, exon number, but nothing much more useful.

> I thought we wanted to import all of this data when the user is setting up the analysis rather than later on?
We can import the data during the functional annotation, or later, but in any case we will need the functionality described by the `TranscriptCoordinateService` interface. So, this ticket is to keep track of the progress on that front.

**Comment by pnrobinson** [comment]
OK.
We should probably ask the user to provide the name of the transcript they consider most important when they start the analysis.

Do you happen to know the best API command that does this? Not entirely obiouvs, if not I will look!

**Comment by ielis** [comment]
I think I found what we need - Variant validator seems to provide what we need:

```shell
curl -X 'GET' \
  'https://rest.variantvalidator.org/VariantValidator/tools/gene2transcripts/NM_003172' \
  -H 'accept: application/json'
```

I went through these before hitting variant validator

- ENSEMBL [REST API](https://rest.ensembl.org/documentation/info/lookup) could give us what we need but it needs a stable Ensembl ID (e.g. ENSG00000012345) but we work in the RefSeq space

- NCBI [Rest API](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/reference-docs/rest-api/) can take RefSeq tx ID but it does not return exon coordinates:
```shell
TX_ID=NM_003172.4 # My favorite RefSeq tx id
curl -X GET "https://api.ncbi.nlm.nih.gov/datasets/v2alpha/gene/accession/${TX_ID}?returned_content=COMPLETE&table_fields=gene-id&table_fields=gene-type&table_fields=description" \
 -H "Accept: application/json"
```

- [genenames.org](https://www.genenames.org/help/rest/) can give you details for a RefSeq ID but it does not provide exon coordinates:
```shell
curl -X GET "https://rest.genenames.org/fetch/refseq_accession/NM_003172" -H "Accept: application/json"
```

- [Variant validator](https://rest.variantvalidator.org/) does not provide exons as well

**Comment by ielis** [comment]
A template:

```python

class VVTranscriptCoordinateService(TranscriptCoordinateService):

    def __init__(self, gb: GenomeBuild):
        self._gb = gb
        self._url = 'https://rest.variantvalidator.org/VariantValidator/tools/gene2transcripts/%s'

    def fetch(self, tx: TranscriptInfoAware) -> TranscriptCoordinates:
        # create query
        query = ''

        contig = 'NC_000009.11'
        contig = self._gb.contig_by_name(contig)
        GenomicRegion()
        return TranscriptCoordinates()

```
