### ISSUE TITLE
Move phenopacket generating code to phenopacket store

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/genophenocorr#90]
I will move the generation to phenopacket store, because then it is easier to reuse the phenopackets for multiple projects. To do so, I will create and check the phenopackets with the updated code and then make a PR that will add the "new" phenopackets to the input folder and delete the phenopacket generation notebook (which I will move and adapt to phenopacket store).
@lnrekerle @ielis  -- please shout if there is a better way of doing things!

**Comment by ielis** [comment]
Sounds good! :+1:

**Comment by ielis** [comment]
Done
