### ISSUE TITLE
Discuss statistical tests

### ISSUE THREAD

**Issue by ielis** [monarch-initiative/genophenocorr#91]
Currently we have Fisher's exact test that works for 2x2 contingency tables. This works OK if we use genotype and phenotype predicates that both categorize patients into 2 categories.

Next, we have Fisher's exact test for 2x3 tables, so we can afford using one predicate with 3 categories.

However, can we extend the framework to predicates with more categories? 

An example of such predicate is a predicate comparing presence of 4 different variants, resulting in 4 categories.

**Comment by pnrobinson** [comment]
This is not something I have ever seen in the literature, and probably it is lower priority. For the first release, let's make sure the 2x2 and the 3x2 work correctly and we can see if any user wants a different test.
Another thing that would be interesting to do would be a numerical test for GA4GH Measurement objects.
