### ISSUE TITLE
Report the number of performed tests in `GenotypePhenotypeAnalysisResult`

### ISSUE THREAD

**Issue by ielis** [monarch-initiative/genophenocorr#98]
When doing multiple tests, knowing how many tests were preformed is a useful information to have.

We should provide the users with a simple way to get the number of performed tests.

This can be implemented as a new `int` property on `GenotypePhenotypeAnalysisResult`.

**Comment by lnrekerle** [comment]
This has been implemented through the Multiple Testing Correction Heuristic.

**Comment by ielis** [comment]
@lnrekerle , for the record, can you please add a comment here with a link to a method/property where we can get the number of performed tests for an analysis?

**Comment by lnrekerle** [comment]
```python
    @staticmethod
    def get_number_of_observed_hpo_observations(counts_frame: pd.DataFrame) -> int:
        return counts_frame.loc[PatientCategories.YES].sum()
``` 

This is in .../analysis/_gp_analysis.py
@pnrobinson could you confirm this is the function you were thinking of when you said I could close this? I'm assuming it's this since each hpo observation would be one test.

**Comment by ielis** [comment]
No, this is not what I had in mind. I would like to see a function (or a property, FWIW) on `GenotypePhenotypeAnalysisResult` that takes no arguments and returns and `int` with the count.

The function should be relatively straightforward to implement, but, as always, we need the function, a spot on doc string, and a test.

Then we can close this as complete.
